<a href="https://colab.research.google.com/github/CinnamonXI/Hamoye-Tasks/blob/master/HamoyeStageB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hamoye Stage B assessment

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [3]:
 url='https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv'
 df= pd.read_csv(url)
 df.head()

                  date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668
3  2016-01-11 17:30:00          50      40  ...        5.0  45.410389  45.410389
4  2016-01-11 17:40:00          60      40  ...        4.9  10.084097  10.084097

[5 rows x 29 columns]

In [4]:
column_names = {
    'T1': 'kitchen_temp_c', 'RH_1': '%kitchen_humidity', 'T2': 'living_room_temp_c', 'RH_2':'%living_room_humidity', 
    'T3': 'laundry_room_temp_c', 'RH_3': '%laundry_room_humidity', 'T4': 'office_room_temp_c',  'RH_4': '%office_room_humidity', 
    'T5': 'bathroom_temp_c', 'RH_5':'%bathroom_humidity', 'T6':'outside_north_side_temp_c', 'RH_6': '%outside_north_side_humidity', 
    'T7': 'ironing_room_temp_c', 'RH_7': '%ironing_room_humidity', 'T8': 'teenager_room_temp_c', 'RH_8': '%teenager_room_humidity', 
    'T9': 'parents_room_temp_c', 'RH_9': '%parents_room_humidity'
}
df= df.rename(columns=column_names)

In [5]:
df.head()

                  date  Appliances  lights  ...  Tdewpoint        rv1        rv2
0  2016-01-11 17:00:00          60      30  ...        5.3  13.275433  13.275433
1  2016-01-11 17:10:00          60      30  ...        5.2  18.606195  18.606195
2  2016-01-11 17:20:00          50      30  ...        5.1  28.642668  28.642668
3  2016-01-11 17:30:00          50      40  ...        5.0  45.410389  45.410389
4  2016-01-11 17:40:00          60      40  ...        4.9  10.084097  10.084097

[5 rows x 29 columns]

In [6]:
df.corr()

                              Appliances    lights  ...       rv1       rv2
Appliances                      1.000000  0.197278  ... -0.011145 -0.011145
lights                          0.197278  1.000000  ...  0.000521  0.000521
kitchen_temp_c                  0.055447 -0.023528  ... -0.006203 -0.006203
%kitchen_humidity               0.086031  0.106968  ... -0.000699 -0.000699
living_room_temp_c              0.120073 -0.005622  ... -0.011087 -0.011087
%living_room_humidity          -0.060465  0.050985  ...  0.006275  0.006275
laundry_room_temp_c             0.085060 -0.097393  ... -0.005194 -0.005194
%laundry_room_humidity          0.036292  0.131161  ... -0.000477 -0.000477
office_room_temp_c              0.040281 -0.008859  ... -0.001815 -0.001815
%office_room_humidity           0.016965  0.114936  ... -0.001787 -0.001787
bathroom_temp_c                 0.019760 -0.078745  ... -0.005490 -0.005490
%bathroom_humidity              0.006955  0.141233  ... -0.011056 -0.011056
outside_north_side_temp_c       0.117638 -0.079029  ... -0.015086 -0.015086
%outside_north_side_humidity   -0.083178  0.153756  ...  0.011671  0.011671
ironing_room_temp_c             0.025801 -0.135347  ... -0.003900 -0.003900
%ironing_room_humidity         -0.055642  0.035069  ...  0.001820  0.001820
teenager_room_temp_c            0.039572 -0.071458  ... -0.003210 -0.003210
%teenager_room_humidity        -0.094039  0.012915  ...  0.004480  0.004480
parents_room_temp_c             0.010010 -0.157592  ... -0.001227 -0.001227
%parents_room_humidity         -0.051462 -0.008766  ... -0.002955 -0.002955
T_out                           0.099155 -0.074424  ... -0.015216 -0.015216
Press_mm_hg                    -0.034885 -0.010576  ...  0.000699  0.000699
RH_out                         -0.152282  0.068543  ...  0.020441  0.020441
Windspeed                       0.087122  0.060281  ... -0.011342 -0.011342
Visibility                      0.000230  0.020038  ... -0.005889 -0.005889
Tdewpoint                       0.015353 -0.036322  ... -0.003943 -0.003943
rv1                            -0.011145  0.000521  ...  1.000000  1.000000
rv2                            -0.011145  0.000521  ...  1.000000  1.000000

[28 rows x 28 columns]

In [7]:
df.describe()

         Appliances        lights  ...           rv1           rv2
count  19735.000000  19735.000000  ...  19735.000000  19735.000000
mean      97.694958      3.801875  ...     24.988033     24.988033
std      102.524891      7.935988  ...     14.496634     14.496634
min       10.000000      0.000000  ...      0.005322      0.005322
25%       50.000000      0.000000  ...     12.497889     12.497889
50%       60.000000      0.000000  ...     24.897653     24.897653
75%      100.000000      0.000000  ...     37.583769     37.583769
max     1080.000000     70.000000  ...     49.996530     49.996530

[8 rows x 28 columns]

In [8]:
df.isnull().sum()

date                            0
Appliances                      0
lights                          0
kitchen_temp_c                  0
%kitchen_humidity               0
living_room_temp_c              0
%living_room_humidity           0
laundry_room_temp_c             0
%laundry_room_humidity          0
office_room_temp_c              0
%office_room_humidity           0
bathroom_temp_c                 0
%bathroom_humidity              0
outside_north_side_temp_c       0
%outside_north_side_humidity    0
ironing_room_temp_c             0
%ironing_room_humidity          0
teenager_room_temp_c            0
%teenager_room_humidity         0
parents_room_temp_c             0
%parents_room_humidity          0
T_out                           0
Press_mm_hg                     0
RH_out                          0
Windspeed                       0
Visibility                      0
Tdewpoint                       0
rv1                             0
rv2                             0
dtype: int64

Question 12

In [9]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler = MinMaxScaler()
normalised_df=df.drop(['date','lights'], axis=1)
normalised_df= pd.DataFrame(scaler.fit_transform(normalised_df), columns=normalised_df.columns)
features_df=normalised_df[['living_room_temp_c']]
target_df=normalised_df[['outside_north_side_temp_c']]

In [30]:
from sklearn.model_selection import train_test_split

In [36]:
x_train, x_test, y_train, y_test= train_test_split(features_df, target_df, test_size=0.3, random_state=42)

In [37]:
lin_model = LinearRegression()
lin_model.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
predict_vals = lin_model.predict(x_test)

In [42]:
lin_model.score(x_train, y_train)

0.6415148739809167

Question 13

In [45]:
mae=mean_absolute_error(y_test, predict_vals)
mae

0.08216970202681717

Question 14

In [48]:
rss= np.sum(np.square(y_test - predict_vals))
rss

outside_north_side_temp_c    66.115579
dtype: float64

Question 15

In [49]:
rmse=np.sqrt(mean_squared_error(y_test,predict_vals))
rmse

0.10567064851347532

Question 16

In [50]:
lin_model.coef_

array([[0.8910771]])

Question 17

In [70]:

features_df1 = normalised_df.drop(columns=['Appliances'])
target_df1 = normalised_df['Appliances']
x_train1, x_test1, y_train1, y_test1 = train_test_split(features_df1, target_df1, test_size=0.3, random_state=42)

       kitchen_temp_c  %kitchen_humidity  ...       rv1       rv2
9129         0.497360           0.236767  ...  0.724554  0.724554
2453         0.286167           0.482616  ...  0.864041  0.864041
9152         0.422386           0.230529  ...  0.499502  0.499502
12694        0.560718           0.446840  ...  0.323173  0.323173
16952        0.835269           0.422071  ...  0.341060  0.341060
...               ...                ...  ...       ...       ...
11284        0.524815           0.381892  ...  0.910318  0.910318
11964        0.591341           0.458949  ...  0.698711  0.698711
5390         0.369588           0.238785  ...  0.381388  0.381388
860          0.527983           0.234933  ...  0.020909  0.020909
15795        0.478705           0.294652  ...  0.349076  0.349076

[13814 rows x 26 columns]

In [66]:
lin_model1=LinearRegression().fit(x_train1,y_train1)
lin_model1.coef_

array([-0.00328105,  0.5535466 , -0.23617792, -0.45669795,  0.29062714,
        0.09604827,  0.028981  ,  0.02638578, -0.01565684,  0.01600579,
        0.23642491,  0.03804865,  0.01031878, -0.04461364,  0.10199505,
       -0.15759548, -0.18994077, -0.03980032, -0.32185967,  0.00683933,
       -0.07767065,  0.02918313,  0.01230661,  0.11775773,  0.0007701 ,
        0.0007701 ])

In [74]:
coefs= pd.DataFrame({'features':x_train1.columns, 'coef': lin_model1.coef_}).sort_values(by='coef')
coefs

                        features      coef
3          %living_room_humidity -0.456698
18                         T_out -0.321860
2             living_room_temp_c -0.236178
16           parents_room_temp_c -0.189941
15       %teenager_room_humidity -0.157595
20                        RH_out -0.077671
13        %ironing_room_humidity -0.044614
17        %parents_room_humidity -0.039800
8                bathroom_temp_c -0.015657
0                 kitchen_temp_c -0.003281
24                           rv1  0.000770
25                           rv2  0.000770
19                   Press_mm_hg  0.006839
12           ironing_room_temp_c  0.010319
22                    Visibility  0.012307
9             %bathroom_humidity  0.016006
7          %office_room_humidity  0.026386
6             office_room_temp_c  0.028981
21                     Windspeed  0.029183
11  %outside_north_side_humidity  0.038049
5         %laundry_room_humidity  0.096048
14          teenager_room_temp_c  0.101995
23                     Tdewpoint  0.117758
10     outside_north_side_temp_c  0.236425
4            laundry_room_temp_c  0.290627
1              %kitchen_humidity  0.553547

Question 18

In [78]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.4)
ridge_reg.fit(x_train1, y_train1)
pred=ridge_reg.predict(x_test1)

In [79]:
rsser=np.sqrt(mean_squared_error(y_test1, pred))
rsser

0.08753385704628003

Question 19

In [80]:
from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.001)
lasso_reg.fit(x_train, y_train)
pred1= lasso_reg.predict(x_test1)

In [81]:
coefs1= pd.DataFrame({'features':x_train1.columns, 'coef': lasso_reg.coef_}).sort_values(by='coef')
coefs1

                        features      coef
20                        RH_out -0.049557
15       %teenager_room_humidity -0.000110
0                 kitchen_temp_c  0.000000
23                     Tdewpoint  0.000000
22                    Visibility  0.000000
19                   Press_mm_hg -0.000000
18                         T_out  0.000000
17        %parents_room_humidity -0.000000
16           parents_room_temp_c -0.000000
14          teenager_room_temp_c  0.000000
13        %ironing_room_humidity -0.000000
24                           rv1 -0.000000
12           ironing_room_temp_c -0.000000
10     outside_north_side_temp_c  0.000000
9             %bathroom_humidity  0.000000
8                bathroom_temp_c -0.000000
7          %office_room_humidity  0.000000
6             office_room_temp_c -0.000000
5         %laundry_room_humidity  0.000000
4            laundry_room_temp_c  0.000000
3          %living_room_humidity -0.000000
2             living_room_temp_c  0.000000
11  %outside_north_side_humidity -0.000000
25                           rv2 -0.000000
21                     Windspeed  0.002912
1              %kitchen_humidity  0.017880

Question 20

In [82]:
rssel=np.sqrt(mean_squared_error(y_test1, pred))
rssel

0.08753385704628003